Iter5
DeneesK/metrics-alerting pull request #5
Opened 2023-05-02 09:06 UTC by DeneesK

2023-05-03 15:03 UTC, s-shpak requested changes
Комментов много, но, в целом, я доволен результатом :)

2023-05-03 15:03 UTC, s-shpak commented on cmd/agent/flags.go
> +	flag.IntVar(&flagreportInterval, "r", 10, "override reportInterval - the frequency of sending metrics to the server")
Обычно в описании флага не указывают, что он что-то переопределяет, дефолтное значение библиотека выведет самотстоятельно

2023-05-03 15:03 UTC, s-shpak commented on cmd/agent/flags.go
> +	flag.IntVar(&flagpolltInterval, "p", 2, "override pollInterval - the frequency of polling metrics from the runtime package")
Смотри выше

2023-05-03 15:03 UTC, s-shpak commented on cmd/agent/flags.go
> +	if envreportInterval := os.Getenv("REPORT_INTERVAL"); envreportInterval != "" {
Здесь лучше использовать `os.LookupEnv`: https://pkg.go.dev/os#LookupEnv

2023-05-03 15:03 UTC, s-shpak commented on cmd/agent/flags.go
> +		fri, _ := strconv.Atoi(envreportInterval)
Ошибки не стоит игнорировать, их надо обработать

2023-05-03 15:03 UTC, s-shpak commented on cmd/agent/flags.go
> +		fpi, _ := strconv.Atoi(envpolltInterval)
Смотри выше

2023-05-03 15:03 UTC, s-shpak commented on cmd/agent/flags.go
> +var flagpolltInterval int
Переменные лучше именовать в CamelCase (https://ru.wikipedia.org/wiki/CamelCase) начиная имя со строчной буквы. Кроме того не совсем понятно, что обозначает буква `t` в этом имени.

И нет смысла добавлять перфикс `flag`: пользователю этой переменной безразлично как она была получена

2023-05-03 15:03 UTC, s-shpak commented on cmd/agent/statsparser.go
> +func ParseNeededStats(ms runtime.MemStats) map[string]float64 {
Это deadcode (https://en.wikipedia.org/wiki/Dead_code), его надо удалять

2023-05-03 15:03 UTC, s-shpak commented on internal/services/metriccollector/collector.go
> +type Collector interface {
Интерфейс стоит объявлять там, где он используется, т.к. интерфейс служит для описания ожидаемого поведения объекта тем, кто этот объект использует

2023-05-03 15:03 UTC, s-shpak commented on internal/services/metriccollector/collector.go
> +	return Metrics{pollInterval: time.Duration(pollInterval)}
Кажется, что было бы проще сразу записать в поле `pollInterval` требуемое значение, а не вычислять его дополнительно при каждом вызове метода `pollMetrics`

2023-05-03 15:03 UTC, s-shpak commented on internal/services/metriccollector/collector.go
> +	time.Sleep(ms.pollInterval * time.Second)
Не очень логично, что именно в этой функции вызывается `time.Sleep`. Хорошей практикой является объявление функций, которые делают что-то одно, но в вашем случае функция и вычисляет метрики, и спит до следующего вычисления. Как вы думаете, куда было бы лучше поместить `time.Sleep`?

2023-05-03 15:03 UTC, s-shpak commented on internal/services/metriccollector/collector.go
> +func (ms *Metrics) GetMetrics() map[string]float64 {
1. Что случится, если во время сбора метрик (в `pollMetrics`), мы попытаемся их отправить на сервер? Как решить эту проблему? Этот вопрос также относится к `GetRandomValue` и к `GetPollCount`
2. Кажется, что представлять все значения в виде `float64` - плохая идея. Хотелось бы иметь возможность возвращать метрики с любыми типами численных значений (тебе нужны только два - float64 и uint64). Как это можно было бы сделать?

2023-05-03 15:03 UTC, s-shpak commented on internal/services/metriccollector/collector.go
> +	m := structs.Map(ms.stats)
Эта библиотека использует рефлексию, потому мы не можем пользоваться ей

2023-05-03 15:03 UTC, s-shpak commented on internal/services/metriccollector/collector.go
> +	mapstats := make(map[string]float64)
Можем ли мы объявить размер этой мапы заранее?

2023-05-03 15:03 UTC, s-shpak commented on internal/services/metriccollector/collector.go
> +		mapstats[stat] = float64(m[stat].(uint64))
Что будет, если type assertion завершится с ошибкой? Как это можно исправить?

2023-05-03 15:03 UTC, s-shpak commented on internal/services/metriccollector/collector.go
> +	mapstats["GCCPUFraction"] = m["GCCPUFraction"].(float64)
Смотри предыдущий комментарий

2023-05-03 15:03 UTC, s-shpak commented on internal/services/metriccollector/collector.go
> +type gauge float64
Не совсем понимаю: в чем смысл объявления этих типов?

2023-05-03 15:03 UTC, s-shpak commented on internal/services/urlpreparer/preparer.go
> +func PrepareURL(basePath string, metricType string, metricName string, value float64) string {
Логировать ошибку внутри функции стоит тогда, когда после этой ошибки функция может продолжить работу, или когда мы находимся на самом верхнем уровне (некому ошибку отдавать). В остальных случаях лучше вернуть ошибку и обработать ее выше.

Если оставить логику как сейчас, то даже несмотря на то, что `PrepareURL` не смог отработать корректно, мы можем попытаться использовать результат его работы, чего делать не стоит.

2023-05-03 15:03 UTC, s-shpak commented on cmd/agent/requests.go
> +		sendReport(session, url)
Ошибки `sendReport` надо обрабатывать

2023-05-03 15:03 UTC, s-shpak commented on internal/services/urlpreparer/preparer.go
> +	v := fmt.Sprintf("%f", value)
Лучше использовать `strconv.FormatFloat` с аргументом `prec = -1`, так в строке будет записано столько цифр, сколько нужно (например, не `1.500000`, а `1.5`)

2023-05-03 15:03 UTC, s-shpak commented on internal/services/urlpreparer/preparer_test.go
> +				value:      1.5},
```suggestion
				value:      1.5,
				},
```

2023-05-03 15:03 UTC, s-shpak commented on cmd/agent/main_test.go
> +		wantContenType string
Опечатка, чтобы их ловить установи расшиение Code Spell Checker (если ты на vscode)

2023-05-03 15:03 UTC, s-shpak commented on cmd/agent/main_test.go
> +			url, _ := url.JoinPath(ts.URL, test.args.url)
Эту ошибку надо проверить

2023-05-03 15:03 UTC, s-shpak commented on cmd/server/flags.go
> +var flagRunAddr string
См комментарий к аналогичному коду агента

2023-05-03 15:03 UTC, s-shpak commented on internal/storage/memory.go
> +		v, _ := strconv.Atoi(value)
Ошибку надо проверить

2023-05-03 15:03 UTC, s-shpak commented on internal/storage/memory.go
> +func (storage *MemStorage) GetValue(typeMetric, name string) string {
1. Было бы неплохо возвращать еше и статус о том, найдено ли значние в storage или нет
2. Было бы неплохо возвращать ошибку, если попытались извлечь метрику неизвестного типа: это позволило бы быстрее обнаружить ошибку во внутренней логике сервера

2023-05-03 15:03 UTC, s-shpak commented on internal/storage/memory.go
> +func (storage *MemStorage) GetAll() string {
Мне кажется, что ответственность за то, как именно выводить метрики, должна быть вне кода  storage: если вы решите поменять формат вывода метрик, вам не надо будет изменять код storage

2023-05-03 15:03 UTC, s-shpak commented on internal/storage/memory.go
> +func (storage *MemStorage) Store(t, name, value string) {
1. Что будет, если попытаться одновременно записать и прочитать одно и то же значение из store? Как этого избежать?
2. Было бы неплохо возвращать ошибку, если попытались извлечь метрику неизвестного типа: это позволило бы быстрее обнаружить ошибку во внутренней логике сервера

2023-05-03 15:03 UTC, s-shpak commented on internal/api/rest.go
> +			if _, err := strconv.Atoi(valueString); err != nil {
Лучше использовать strconv.ParseInt, т.к. она сразу возвращает тот тип, который ожидается

2023-05-03 15:03 UTC, s-shpak commented on internal/api/rest.go
> +		res.Header().Add("Content-Type", "text/plain; charset=utf-8")
Этот Content-Type стоит вынести в константу

2023-05-03 15:20 UTC, s-shpak commented on internal/services/metriccollector/collector.go
> +	ms.pollCount += 1
Забыл сказать: текст задания сформулирован несколько некорректно, метрика `pollCount` на сервере должна отражать реальное количество операций сбора метрик, в текущей реализации это не так. Подумай, как это исправить

2023-05-04 18:33 UTC, s-shpak requested changes

2023-05-04 18:33 UTC, s-shpak commented on cmd/agent/flags.go
> +var RunAddr string
Эти значения необязательно делать экспортируемыми

2023-05-04 18:33 UTC, s-shpak commented on cmd/agent/flags.go
> +			log.Fatal("The value of the REPORT_INTERVAL environment variable is not a integer.")
Это не очень хороший способ обработать ошибку. Обычно в Go критические ошибки (которые не позволяют продолжить выполнение программы) возвращаются из функции и доходят до самого верхнего уровня (до функции main или, если речь идет об отдельной горутине, до функции которая была в ней запущена), где они логируются, и программа завершается.

Не стоит выходить из программы где-то в глубине логики:
1. Код сложнее читать, лучше, когда понятно, где именно точка выхода
2. Не получится завершить сторонние процессы штатным образом, что может привести к проблемам

2023-05-04 18:33 UTC, s-shpak commented on internal/services/urlpreparer/preparer.go
> +		return "", fmt.Errorf("PrepareURL failed: %v", err)
Не стоит помещать имя функции в сообщение об ошибке: имя функции может измениться и придется править и ошибку

2023-05-04 18:33 UTC, s-shpak commented on cmd/agent/requests.go
> +		if err != nil {
В Go если значение возвращенной ошибки не нулевое использовать результат работы функции, как правило, нельзя. Эту ошибку стоит прокинуть выше (ее можно еще и обернуть в новое сообщение)

2023-05-04 18:33 UTC, s-shpak commented on cmd/agent/requests.go
> +			log.Println(err)
Смотри выше

2023-05-04 18:33 UTC, s-shpak commented on cmd/server/flags.go
> +var RunAddr string
Не стоит делать эту переменную экспортируемой

2023-05-04 18:33 UTC, s-shpak commented on internal/storage/memory.go
> +func (storage *MemStorage) Store(type_, name, value string) error {
1. Лучше выбирать одно и то же имя для переменной с типом метрики, `typeMetric` лучше, чем `type_`, потому что без подчеркивания. `metricType` еще лучше, потому что понятнее
2. Было бы неплохо возвращать ошибку, если попытались извлечь метрику неизвестного типа: это позволило бы быстрее обнаружить ошибку во внутренней логике сервера

2023-05-04 18:33 UTC, s-shpak commented on internal/storage/memory.go
> +			return ErrCounterValue
В сообщение об ошибке можно еще обернуть изначальую ошибку и добавить значение из-за которого ошибка произошла: `return fmt.Errorf("failed to convert value %s to an integer: %w", err)`

Объявлять новые ошибки при этом необязательно (`ErrCounterValue`) можно удалить.

Этот комментарий касается и других подобных случаев в коде

2023-05-04 18:33 UTC, s-shpak commented on internal/storage/memory.go
> +	return g.g
Теперь появилась другая проблема: когда caller получит эту мапу и начнет ее использовать, она больше не будет защищена мьютексом, и race condition вновь станет возможным

2023-05-04 18:33 UTC, s-shpak commented on internal/storage/memory.go
> +	return c.c
Смотри такой же комментарий для `gauge`

2023-05-04 18:33 UTC, s-shpak commented on internal/services/urlpreparer/preparer_test.go
> +			fmt.Println(err)
Ты, скорее всего, забыл убрать этот `Println`

2023-05-07 12:14 UTC, s-shpak requested changes

2023-05-07 12:14 UTC, s-shpak commented on internal/storage/memory.go
> +var ErrMetricType = errors.New("metric type does not exist")
Эта ошибка нигде, кроме этого пакета, не используется, т.е.
1. ее можно сделать неэкспортируемой
2. ее можно вообще пока убрать и возвращать ошибку через `fmt.Errorf`

2023-05-07 12:14 UTC, s-shpak commented on internal/storage/memory.go
> +		return fmt.Sprintf("%d", v), true, nil
Преобразовывать числа в строку лучше через `strconv.Format*` - это быстрее

2023-05-07 12:14 UTC, s-shpak commented on internal/storage/memory.go
> +	if ok := checkMetricType(metricType); !ok {
Эта проверка не нужна, потоу что в `switch` ты ее повторяешь

2023-05-07 12:14 UTC, s-shpak commented on internal/storage/memory.go
> +	if ok := checkMetricType(metricType); !ok {
Эта проверка не нужна, потоу что в switch ты ее повторяешь

2023-05-07 12:14 UTC, s-shpak commented on cmd/agent/requests.go
> +	reportInterval time.Duration = time.Second * time.Duration(reportingInterval)
Этот `reportInterval` всегда нулевой

2023-05-07 12:14 UTC, s-shpak commented on cmd/agent/requests.go
> +func sendMetrics(ms Collector) error {
В этой функции очень много повторяющегося кода, который можно вынести в отдельную функцию

2023-05-07 12:14 UTC, s-shpak commented on internal/services/metriccollector/collector.go
> +	ms.randomValue = float64(rand.Float32())
Почему не `rand.Float64()` ?

2023-05-07 12:14 UTC, s-shpak commented on internal/services/metriccollector/collector.go
> +		ms.pollCount += 1
Проблема с некорректнм значением `pollCount` на сервере не решена

2023-05-07 12:14 UTC, s-shpak commented on internal/services/urlpreparer/preparer.go
> +func PrepareURL(basePath string, metricType string, metricName string, value interface{}) (string, error) {
Много повторяющегося кода, можно вынести в отдельую функцию

2023-05-07 12:14 UTC, s-shpak commented on internal/services/urlpreparer/preparer_test.go
> +			want:  want{"http://localhost:8080/update/gauge/metric/1.5"},
```suggestion
			want:  want{"http://localhost:8080/update/gauge/metric/1.5",
			},
```

2023-05-07 14:35 UTC, DeneesK commented on internal/services/metriccollector/collector.go
> +		ms.pollCount += 1
Как я понял, ключевое - **_на сервере_**.

2023-05-07 14:38 UTC, s-shpak commented on internal/services/metriccollector/collector.go
> +		ms.pollCount += 1
Попробуй запустить агент и сервер и через несколько подтягиваний данных на сервер выведи `pollCount` на агенте и ту же метрику на сервере - они не будут одинаковыми. Это н выявляет проблему, но не является ей: сервер должен возвращать количество поллингов на агенте

2023-05-07 15:31 UTC, DeneesK commented on internal/services/metriccollector/collector.go
> +		ms.pollCount += 1
До меня наконец-то дошло🤦‍♂️🤦‍♂️🤦‍♂️

2023-05-08 09:55 UTC, s-shpak requested changes

2023-05-08 09:55 UTC, s-shpak commented on internal/services/metriccollector/collector.go
> +	ms.pollCount = 0
Кажется, что сбрасывать значение в 0 здесь - плохая идея: например, у нас может возникнуть ошибка при отправке данных, тогда мы потеряем раннее накопленные значения. Лучше было бы, наверное, объявить отдельный метод `ResetPollCount`, который позволил бы сбрасывать значение после проверки, что сервер получил очередную порцию метрик.

2023-05-08 10:52 UTC, s-shpak approved these changes

2023-05-08 12:19 UTC, merged