Iter9
DeneesK/metrics-alerting pull request #9
Opened 2023-05-24 11:36 UTC by DeneesK

2023-05-24 17:34 UTC, s-shpak requested changes

2023-05-24 17:34 UTC, s-shpak commented on cmd/agent/requests.go
> -	counterMetric string = "counter"
Часть этих переменных может быть объявлена константами

2023-05-24 17:34 UTC, s-shpak commented on cmd/agent/requests.go
> +	ro := grequests.RequestOptions{Headers: map[string]string{"Content-Encoding": encodeType, "Content-Type": contentType}}
Клиент должен поддерживать получение сжатых ответов

2023-05-24 17:34 UTC, s-shpak commented on cmd/agent/requests.go
> +	switch metricType {
1. Что если тип не `counter` и не `gauge`?
2.В свитче много повторений кода, может можно как-то зарефакторить?

2023-05-24 17:34 UTC, s-shpak commented on cmd/agent/requests.go
> +	resp, err := session.Post(url, &grequests.RequestOptions{JSON: r})
Ответ нужно закрывать

2023-05-24 17:34 UTC, s-shpak commented on cmd/server/flags.go
>  var runAddr string
Давай удем от глобальных переменных к единому конфигурационному объекту, который будет возвращать функция `parseFlags`

2023-05-24 17:34 UTC, s-shpak commented on cmd/server/flags.go
> +	if envStoreInterval, ok := os.LookupEnv("STORE_INTERVAL"); ok {
Почему ты везде используешь `Getenv`, а здесь `LookupEnv`?

2023-05-24 17:34 UTC, s-shpak commented on cmd/server/flags.go
> +			return err
Почему бы просто не `return fmt.Errorf` ?

2023-05-24 17:34 UTC, s-shpak commented on cmd/server/main.go
> +		log.Fatal(err)
Не стоит использовать несколько логгеров - если используешь zap, то лучше везде

2023-05-24 17:34 UTC, s-shpak commented on cmd/server/flags.go
> +	flag.StringVar(&isRestore, "r", "true", "load saved data")
Можно сразу парсить bool

2023-05-24 17:34 UTC, s-shpak commented on cmd/server/main.go
> +		if err != nil {
Лучше запускать горутину в этой функции: тогда ты сможшь сделать все проверки наошибки до ее запуска и выйти, если это будет нужно

2023-05-24 17:34 UTC, s-shpak commented on cmd/server/main.go
> +	storeInterval := time.Duration(storeInterval) * time.Second
Если `storeInterval` будет равен нулю, то функция будет отрабатывать некорректно. Лучше вообщ отключить переодическое сохранение, если `storeInterval` == 0

2023-05-24 17:34 UTC, s-shpak commented on cmd/server/main.go
> +			logger.Error(err)
Очень сложно будет понять откуда взялась ошибка: ее лучше обернуть  в какое-то сообщение

2023-05-24 17:34 UTC, s-shpak commented on internal/api/middlewares.go
> +	w  http.ResponseWriter
Если "встроить" это поле в структуру, то не придется переопределять методы, которые не изменяются по сравнению с `http.ResponseWriter`

2023-05-24 17:34 UTC, s-shpak commented on internal/api/middlewares.go
> +	return c.zw.Close()
Нужно закрывать и `w`

2023-05-24 17:34 UTC, s-shpak commented on internal/api/middlewares.go
> +				w.WriteHeader(http.StatusInternalServerError)
Здесь ошибку стоит залогировать

2023-05-24 17:34 UTC, s-shpak commented on internal/api/rest.go
> +func RouterWithoutMiddlewares(ms Store) chi.Router {
Это тестовый функционал, он не должен попадать в основной код

2023-05-24 17:34 UTC, s-shpak commented on internal/api/rest.go
> +			value, ok, err := storage.GetValue(metric.MType, metric.ID)
Сначала стоит проверять ошибку

2023-05-24 17:34 UTC, s-shpak commented on internal/api/rest.go
> +			if ok {
Если false, то это, наверное, ошибка

2023-05-24 17:34 UTC, s-shpak commented on internal/api/rest.go
> +		if err != nil {
См. предыдущий комментарий

2023-05-24 17:34 UTC, s-shpak commented on internal/api/rest.go
> +				res.Write([]byte(strconv.FormatFloat(value.Gauge, byte(102), -3, 64)))
кажется, что выставлять precision в -3 здесь - не очень хорошая идея, лучше отдавать максимально точное число

2023-05-24 17:34 UTC, s-shpak commented on internal/logger/logger.go
> +		panic(err)
Не надо паниковать

2023-05-24 17:34 UTC, s-shpak commented on internal/logger/logger.go
> +	logFn := func(w http.ResponseWriter, r *http.Request) {
Не создавай новую переменную: либо вынеси в отдельную функцию, либо перенеси прямо в вызов `http.HandlerFunc`

2023-05-24 17:34 UTC, s-shpak commented on internal/logger/logger.go
> +		start := time.Now()
start надо начинать отсчитывать непоредственно перед `ServeHTTP`

2023-05-24 17:34 UTC, s-shpak commented on internal/storage/memory.go
> +func (storage *MemStorage) SaveToFile(path string) error {
Жаль, что интерфейс начинает разрастаться, кажется, что остальному коду необязательно вызывать `SaveToFile` явно, store сам может это делать

2023-05-24 17:34 UTC, s-shpak commented on internal/storage/memory.go
> +	if _, err := os.Stat(path); os.IsNotExist(err) {
Эта проверка не особо помогает: представь, что ты провел ее, сразу после файл удалили, и твой код заходит в `loadFromFile`: эта проверка как минимум бесполезна, `loadFromFile` должен сам обрабатывать ситуацию, когда файла нет

2023-05-26 12:09 UTC, DeneesK commented on internal/api/middlewares.go
> +	w  http.ResponseWriter
Тут немного не понятно, http.ResponseWriter это же интерфейс, встроя его в структуру нам все равно надо определить эти методы?

2023-05-26 12:10 UTC, DeneesK commented on internal/api/middlewares.go
> +	return c.zw.Close()
Сергей, "w" -  это же http.ResponseWriter интерфейс, у него нет Close

2023-05-28 10:27 UTC, s-shpak commented on internal/api/middlewares.go
> +	w  http.ResponseWriter
Нет, так как в инициализации ты будешь передавать конкретную имплементацию в поле с типом интрефейс, она и будет использоваться

2023-05-28 10:27 UTC, s-shpak commented on internal/api/middlewares.go
> +	return c.zw.Close()
my bad

2023-05-28 10:45 UTC, s-shpak requested changes

2023-05-28 10:45 UTC, s-shpak commented on internal/api/middlewares.go
> +				log.Errorf("During compression error ocurred - %v")
Ты забыл передать ошибку параметром

2023-05-28 10:45 UTC, s-shpak commented on internal/api/rest.go
> +				res.Write([]byte(strconv.FormatFloat(value.Gauge, byte(102), -1, 64)))
```suggestion
				res.Write([]byte(strconv.FormatFloat(value.Gauge, 'f', -1, 64)))
```

2023-05-28 10:45 UTC, s-shpak commented on cmd/agent/requests.go
> +	m.ID = metricName // перенеси сразу в структуру
Комментарий можно удалить

2023-05-28 10:45 UTC, s-shpak commented on cmd/server/main_test.go
> +		t.Run(test.name, func(t *testing.T) {
Перед этой строкой лучше добавить `test := test`

2023-05-28 10:45 UTC, s-shpak commented on cmd/server/main_test.go
> +		log.Fatal(err)
В тестах стоит аварийно завершать тест с ошибкой через `t.Fatal`, хотя лучще использовать `t.Error` + `return`

2023-05-28 10:45 UTC, s-shpak commented on internal/api/rest.go
> +type apiLogger interface {
я подумал еще раз и понял, что не стоит определять такой интерфейс - работай лучше напрямую с логгером

2023-05-28 10:45 UTC, s-shpak commented on internal/api/rest.go
> +		if err != nil {
Если `err` не равно нулю, то надо завершаться с ошибкой. Если !ok, то тоже.  Попробуй сделать код в этом файле более плоским

2023-05-28 10:45 UTC, s-shpak commented on internal/storage/memory.go
> +type storageLogger interface {
Аналогично, используй логгер напрямую

2023-05-28 10:45 UTC, s-shpak commented on internal/storage/memory.go
> +	if filePath != "" && storeInterval != 0 {
Я бы делал немного по-другому, если будешь брать one-on-one, то можем обсудить как. Этот коммент можно зарезолвить

2023-05-29 16:23 UTC, s-shpak commented on cmd/server/main_test.go
> +		t.Run(test.name, func(t *testing.T) {
См. такую же проблему в агенте

2023-05-29 16:31 UTC, s-shpak requested changes
Обрати, пожалуйста, внимание на предыдущие незарезолвленные комменты

2023-05-29 16:31 UTC, s-shpak commented on cmd/agent/requests.go
> +		return err
Ошибки из сторонних пакетов надо оборачивать

2023-05-29 16:31 UTC, s-shpak commented on cmd/agent/requests.go
> +	gz.Close()
Здесь надо проверить ошибку

2023-05-29 16:31 UTC, s-shpak commented on cmd/server/main_test.go
> +var metricCounter int64 = 1
Глобальные переменные не нужны

2023-05-29 16:31 UTC, s-shpak commented on internal/api/middlewares.go
> +		ow := w
Зачем? В го все параметры передаются копированием, ты уже скопировал `w` один раз, создавать новую переменную нет смысла

2023-05-29 16:31 UTC, s-shpak commented on internal/logger/logger.go
> +var Sugar zap.SugaredLogger
Глобальные переменные не нужны. Нет ничего страшного в том, чтобы передавать логгер отдельным параметром

2023-05-31 20:06 UTC, s-shpak requested changes

2023-05-31 20:06 UTC, s-shpak commented on internal/logger/logger.go
> +	logger := zap.Must(cfg.Build())
`Must` не надо спользовать, в случае ошибки она выбросит панику

2023-06-01 10:35 UTC, s-shpak requested changes

2023-06-01 10:35 UTC, s-shpak commented on internal/api/rest.go
> +		switch metric.MType {
`default`

2023-06-01 10:35 UTC, s-shpak commented on internal/api/rest.go
> +		switch metricType {
`default`

2023-06-01 10:35 UTC, s-shpak commented on internal/storage/memory.go
> +		v := value.(int64)
Необходимо проверить, что assertion был успешен

```suggestion
		v, ok := value.(int64)
```

2023-06-01 10:35 UTC, s-shpak commented on internal/storage/memory.go
> +		err := os.Mkdir(dir, 0666)
лучше MkdirAll

2023-06-04 09:20 UTC, s-shpak approved these changes
LGTM!

2023-06-04 10:06 UTC, merged